POST http://localhost:9090/projects/662027683b43c8586ba29453/lists
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjFlYjcyNzg0NTQyMjBlN2Q1YWU4YzkiLCJpYXQiOjE3MTMzODEyMzgsImV4cCI6MTcxMzQ2NzYzOH0.sK3kJIUHYdIE993o3wmnRXDik8_ZEPNm0fV64TPjal4

{
    "title": "Lista_1",
    "tasksLimit": 5
}
####

GET http://localhost:9090/lists
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjFlYjcyNzg0NTQyMjBlN2Q1YWU4YzkiLCJpYXQiOjE3MTMzODEyMzgsImV4cCI6MTcxMzQ2NzYzOH0.sK3kJIUHYdIE993o3wmnRXDik8_ZEPNm0fV64TPjal4
####

GET http://localhost:9090/lists/662004972c06e7bc7a1c202e
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjFlYjcyNzg0NTQyMjBlN2Q1YWU4YzkiLCJpYXQiOjE3MTMzODEyMzgsImV4cCI6MTcxMzQ2NzYzOH0.sK3kJIUHYdIE993o3wmnRXDik8_ZEPNm0fV64TPjal4
####

PATCH http://localhost:9090/lists/66202589dc2476cbea0b13f4
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjFlYjcyNzg0NTQyMjBlN2Q1YWU4YzkiLCJpYXQiOjE3MTMzODEyMzgsImV4cCI6MTcxMzQ2NzYzOH0.sK3kJIUHYdIE993o3wmnRXDik8_ZEPNm0fV64TPjal4

{
    "title": "Lista_2"
}
####

DELETE http://localhost:9090/projects/662027683b43c8586ba29453/lists/6620297eb9c3d01a6ef5aa29
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjFlYjcyNzg0NTQyMjBlN2Q1YWU4YzkiLCJpYXQiOjE3MTMzNzQzMjAsImV4cCI6MTcxMzQ2MDcyMH0.edkx4OqU7WcEVn5rifYXvYbCIkQXjdAqdk-lPLnCS1M
####