POST http://localhost:9090/projects/:projectId/lists
Content-Type: application/json
Authorization: 

{
    "title": "Lista_1",
    "tasksLimit": 5
}
####

GET http://localhost:9090/lists
Authorization: 
####

GET http://localhost:9090/lists/
Authorization: 
####

PATCH http://localhost:9090/lists/
Content-Type: application/json
Authorization: 

{
    "title": "Lista_2"
}
####

DELETE http://localhost:9090/projects/:projectId/lists/
Authorization: 
####