POST http://localhost:9090/projects
Content-Type: application/json
Authorization: 

{
    "title": "Progetto_1",
    "description": "Descrizione_1"
}
####

GET http://localhost:9090/projects
Authorization: 
####

GET http://localhost:9090/projects/
Authorization: 
####

PATCH http://localhost:9090/projects/
Content-Type: application/json
Authorization: 

{
    "title": "Progetto_1"
}
####

DELETE http://localhost:9090/projects/
Authorization: 
####