POST http://localhost:9090/users
Content-Type: application/json

{
    "firstName": "Eusebio",
    "lastName": "Walker",
    "username": "EusebioWalker",
    "email": "eusebio.walker54@ethereal.email",
    "password": "9gzczxaJspea5PDENm!"
}
####

GET http://localhost:9090/users
Authorization: 
####

GET http://localhost:9090/users/
Authorization: 
####

PATCH http://localhost:9090/users/
Content-Type: application/json
Authorization: 

{
    "firstName": "Luca"
}
####

DELETE http://localhost:9090/users/
Authorization: 
####

PATCH http://localhost:9090/users/:id/changePassword
Content-Type: application/json
Authorization: 

{
    "currentPassword": "MyPass123!",
    "newPassword": "NewPass123!",
    "confirmNewPassword": "NewPass123!"
}
####