POST http://localhost:9090/users
Content-Type: application/json

{
    "firstName": "Kevin",
    "lastName": " Santoro",
    "username": "User_3",
    "email": " test_3@gmail.com ",
    "password": "MyPass123!"
}
####

GET http://localhost:9090/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjFlYjcyNzg0NTQyMjBlN2Q1YWU4YzkiLCJpYXQiOjE3MTMyODk1NzksImV4cCI6MTcxMzM3NTk3OX0.qphwkJR943VLQ8EWYMl-C5OHXuGP6rW1M-aapg0Z40s
####

GET http://localhost:9090/users/661eb7408454220e7d5ae8cd
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjFlYjcyNzg0NTQyMjBlN2Q1YWU4YzkiLCJpYXQiOjE3MTMyODk1NzksImV4cCI6MTcxMzM3NTk3OX0.qphwkJR943VLQ8EWYMl-C5OHXuGP6rW1M-aapg0Z40s
####

PATCH http://localhost:9090/users/661eb7408454220e7d5ae8cd
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjFlYjcyNzg0NTQyMjBlN2Q1YWU4YzkiLCJpYXQiOjE3MTMyODk1NzksImV4cCI6MTcxMzM3NTk3OX0.qphwkJR943VLQ8EWYMl-C5OHXuGP6rW1M-aapg0Z40s

{
    "fistName": "Luca"
}
####

DELETE http://localhost:9090/users/661b9d3acb98d06a4eb824fb
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjFlYjcyNzg0NTQyMjBlN2Q1YWU4YzkiLCJpYXQiOjE3MTMyODk1NzksImV4cCI6MTcxMzM3NTk3OX0.qphwkJR943VLQ8EWYMl-C5OHXuGP6rW1M-aapg0Z40s
####